### ISSUE TITLE
`Could not create '/var/local/run/qemu-ga.pid': Permission denied `

### ISSUE THREAD

**Issue by bjackman** [danobi/vmtest#101]
Running on a Debian Testing system, 6.9 host kernel 6.12 guest kernel, [guest config](https://github.com/user-attachments/files/17995197/config.txt)

I started getting the `init.sh` failing with `critical: Could not create '/var/local/run/qemu-ga.pid': Permission denied`.

Config looks like this:

```toml
[[target]]
name = "x86 mm selftests"
kernel = "arch/x86/boot/bzImage"
kernel_args = "asi=on pti=off"
command = """
./run_vmtests.sh -t cow
cd /mnt/kselftest_install/mm/
"""
```

IIUC the base 9pfs is my host rootfs, which looks like this (basically looks the same as the `/run` and `/var/run` set up by the vmtest init script, except with funny owners on `/var/run`):

```
❯❯  ls -l /var/run
lrwxrwxrwx 1 root loas-corp-daemons 4 Sep 23  2020 /var/run -> /run/

❯❯  ls -l / | grep run
drwxr-xr-x   57 root   root                     1780 Dec  3 15:21 run

❯❯  mount | grep run | head -1
tmpfs on /run type tmpfs (rw,nosuid,nodev,noexec,relatime,size=18565544k,mode=755,inode64)
```

Just in case, I tried modifying the `/run` mount opts in the `init.sh` template to add `rw`, but no change. I also tried just changing the `qemu-qa` command to put the pidfile in /tmp but there's a bunch more files it wants to drop in `/var/local/run`.

I have a patch that fixes this for me which I'll send now, but I think it might be garbage so raising an issue too so the details are recorded...
