### ISSUE TITLE
"PASS" printed for failing tests

### ISSUE THREAD

**Issue by bjackman** [danobi/vmtest#103]
Hi I'm back, sorry for the spam lately!

When I run a test config like this

```toml
[[target]]
name = "fail"
kernel = "bzImage"
command = "exit 1"                                                                                                                                                                                                 
````

`vmtest` exits with code 1, but the output says `PASS`. When writing the output to a file this is just mildly confusing (I never even noticed it until now), but when you're running `vmtest` directly in the console it's more problematic because you don't really see the output of the test, you just see `PASS` and hope you notice the error return code.

Looking at `Ui::target_ui`, it actually seems like this might be intentional?

```rust
                            // Do not increment the error counter here. The VM ran successfully, the error is convyed by
                            // the command return code.
                            // Nevertheless, we still want to make it clear to the user by logging to the console.
// ...
        if errors == 0 && !show_cmd {
            clear_last_lines(&term, stages);
            term.write_line("PASS").expect("Failed to write terminal");
        } else if !show_cmd {
```

So I have a feeling I'm missing something here. The `README` seems to suggest it should print `FAILED`.
