### ISSUE TITLE
Please replace command string with array

### ISSUE THREAD

**Issue by safinaskar** [danobi/vmtest#5]
Hi. I just read this config in your blog:
```toml
[[target]]
name = "check if kernel is 6.2"
kernel = "./bzImage-v6.2"
command = "/bin/bash -c 'uname -r | grep -e ^6.2.0$'"
```
I don't like this config. It seems that `command` key is meant to be passed directly to `execve` function (as opposed to command, which needs to be interpreted by shell). But then command is conceptually an array, not a string! So, please, replace with this (toml syntax allows this):
```toml
command = ["/bin/bash", "-c", "uname -r | grep -e ^6.2.0$"]
```
